### ISSUE TITLE
Bad substitution error when starting the pool

### ISSUE THREAD

**Issue by ShurikAg** [ZeroASIC/eloipool-server#5]
First  , I want to thank you for putting this together. And I guess I am opening a first issue for you.

When I run:

```
sh startpool.sh
```

I am getting an error:

```
startpool.sh: 3: startpool.sh: Bad substitution
startpool.sh: 4: startpool.sh: Bad substitution
Bitcoin server starting
eloipool.py: no process found
root@mining-pool:/opt/eloipool-server/scripts# nohup: redirecting stderr to stdout
```

However, bitcoind is running but eloipool is not:

```
root@mining-pool:/opt/eloipool-server/scripts# ps aux | grep bitcoin
root      1950 10.0  8.2 819268 168604 ?       SLsl 03:11   0:11 /usr/bin/bitcoind -datadir=/opt/eloipool-server/scripts/../bitcoindata -daemon -blocknotify=/opt/eloipool-server/scripts/newblock.sh
root      1996  0.0  0.0   9388   928 pts/0    S+   03:13   0:00 grep --color=auto bitcoin
```

If I am running run-bitcoind.sh and run-eloipool.sh  separately, I am getting the same result.

Please, advice.

Thanks,

**Comment by ZeroASIC** [comment]
No, this is not the first issue someone has posted.

What version of Ubuntu are you running and  is it up to date?  Did you let bitcoind finish syncing to the network?  A simple Google search indicates exactly what I suspect, you might not be running this in Bash.  

You only checked for bitcoin,  is eloipool running?
$ ps aux | grep -i eloipool

Make sure that bitcoind has finished syncing to the network and then either restart the machine completely or kill all of the erroneous processes that you started and try it again.  Stop running the scripts repeatedly and only run them in Bash because they're bash scripts.

Only run this script one time before ending the processes manually.
$ scripts/startpool.sh

**Comment by ShurikAg** [comment]
OK, perfect! It did work with bash.

How can I check  that bitcoind has finished syncing?
